### ISSUE TITLE
address already in use :::35729

### ISSUE THREAD

**Issue by wangwhcore** [docsifyjs/docsify#1410]
#### Steps to reproduce
1、i start a docsify server  ,and it run normally
2、then i stat another  docsify  server by  ” docsify serve --port 3001 docs“
3、finally ，i get a error msg ” Error: listen EADDRINUSE: address already in use :::35729“

#### What is current behaviour
address already in use

full stack is：
------------------------------------------------------------------------------
Serving D:\xxx\docs\markdown\doc-front\docs now.
Listening at http://localhost:3001

events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::35729
    at Server.setupListenHandle [as _listen2] (net.js:1279:14)
    at listenInCluster (net.js:1327:12)
    at Server.listen (net.js:1414:7)
    at Server.listen (E:\pubsoft\npms\node_modules\docsify-cli\node_modules\livereload\lib\livereload.js:80:28)
    at Object.exports.createServer (E:\pubsoft\npms\node_modules\docsify-cli\node_modules\livereload\lib\livereload.js:246:14)
    at Object.module.exports [as serve] (E:\pubsoft\npms\node_modules\docsify-cli\lib\commands\serve.js:30:12)
    at Object.handler (E:\pubsoft\npms\node_modules\docsify-cli\bin\docsify:77:28)
    at Object.self.runCommand (E:\pubsoft\npms\node_modules\docsify-cli\node_modules\yargs\lib\command.js:231:22)
    at Object.Yargs.self._parseArgs (E:\pubsoft\npms\node_modules\docsify-cli\node_modules\yargs\yargs.js:990:30)
    at Object.get [as argv] (E:\pubsoft\npms\node_modules\docsify-cli\node_modules\yargs\yargs.js:930:19)
Emitted 'error' event at:
    at Server.onError (E:\pubsoft\npms\node_modules\docsify-cli\node_modules\livereload\lib\livereload.js:99:19)
    at WebSocketServer.emit (events.js:198:13)
    at Server.WebSocketServer._onServerError (E:\pubsoft\npms\node_modules\docsify-cli\node_modules\ws\lib\WebSocketServer.js:82:50)
    at Server.emit (events.js:198:13)
    at emitErrorNT (net.js:1306:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

------------------------------------------------------------------------------
#### What is the expected behaviour
i want  run  more  docsify  on one  linux computer 

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS:  windows 10
- Node.js version:  latest
- npm/yarn version: 
- Browser version: 
- Docsify version: 
- Docsify plugins: 

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by sy-records** [comment]
I can't reproduce. What was the entire command you used?

See your error message is windows, what about under linux?

**Comment by wangwhcore** [comment]
i have  two  docsify  sever  ， the is for   dev doc   ，the another is for  front doc。


so ，i  copy the first docsify（dev doc） to a new folder （rename it as   ”front-doc“），and use   ”docsify serve --port  3002 docs “ to start the front-doc docsifyServer






when i start in linux ，i get the same  error







thanks

At 2020-10-28 17:52:21, "沈唁" <notifications@github.com> wrote:

I can't reproduce. What was the entire command you used?

See your error message is windows, what about under linux?

**Comment by sy-records** [comment]
I can't reproduce. Can you provide a reproduction of the repo?

**Comment by jhildenbiddle** [comment]
Also unable to reproduce using docsify-cli 4.4.1. Tried three separate terminal windows, all serving the same directly using the following command:

```
npx docsify-cli serve ./
```
