### ISSUE TITLE
The SSR example failed

### ISSUE THREAD

**Issue by yl-yue** [docsifyjs/docsify#1413]
invalid https://docsify.now.sh/

**Comment by sy-records** [comment]
Thanks for your feedback, we'll try to fix it in the next version.

**Comment by trusktr** [comment]
There is a PR in progress for this: #1227

**Comment by yl-yue** [comment]
After starting with `npm start`, the access reports an error：
```
[root@iZ8vbl0q91x1xZ ssr]# npm start

> docsify-ssr@1.0.0 start /root/ssr
> docsify start . -c ssr.config.js


[SSR] Serving . now.
Listening at http://localhost:4000

TypeError: Cannot read property 'indexOf' of undefined
    at AbstractHistory.parse (/root/ssr/node_modules/docsify-server-renderer/build.js:297:27)
    at Compiler.compile (/root/ssr/node_modules/docsify-server-renderer/build.js:857:37)
    at Renderer.<anonymous> (/root/ssr/node_modules/docsify-server-renderer/build.js:1431:28)
    at Generator.next (<anonymous>)
    at c (/root/ssr/node_modules/docsify-server-renderer/build.js:16:99)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

The configuration is based on [docsify-ssr-demo](https://github.com/docsifyjs/docsify-ssr-demo), with only the basePath property changed

```js
module.exports = {
  template: './ssr.html',
  maxAge: 60 * 60 * 1000,
  config: {
    basePath: 'https://ylyue.cn/',
    auto2top: true,
    coverpage: true,
    executeScript: true,
    loadSidebar: true,
    loadNavbar: true,
    mergeNavbar: true,
    maxLevel: 4,
    subMaxLevel: 2,
    name: 'docsify'
  }
}
```

**Comment by sy-records** [comment]
deleted SSR. see #2105
