### ISSUE TITLE
Search not work with relativePath and routerMode hash

### ISSUE THREAD

**Issue by rottmann** [docsifyjs/docsify#1764]
#### Steps to reproduce

Config:
```
relativePath: true
routerMode: hash
basePath: /
```
Open a doc `http://localhost:3000/#/`

#### What is current behaviour

Error:
```
docsify.js:466 Uncaught TypeError: Cannot read properties of undefined (reading 'substring')
    at HashHistory.toURL (docsify.js:466:37)
    at HashHistory.toURL (docsify.js:579:44)
    at search.js:142:25
    at Array.forEach (<anonymous>)
    at genIndex (search.js:133:12)
    at search.js:348:26
    at XMLHttpRequest.<anonymous> (docsify.js:2264:13)
```

**Comment by Koooooo-7** [comment]
Hi, I make the same config but it works fine.
Could provide more details about it, may be in the `sandbox`?
