### ISSUE TITLE
docsify-server-renderer error

### ISSUE THREAD

**Issue by ccforeverd** [docsifyjs/docsify#704]
My code here:

``` js
// docs-renderer.js
const fs = require('fs')
const path = require('path')
const docsifyRenderer = require('docsify-server-renderer')
const templatePath = path.resolve(__dirname, '../../docs/index.template.html')

const docsifyConfig = {
  basePath: '/src',
  // ...
}

const renderer = new docsifyRenderer({
  template: fs.readFileSync(templatePath, 'utf-8'),
  config: docsifyConfig
})

async function test () {
  renderer.renderToString('docs/')
    .then(console.log)
    .catch(console.log)
}

test()

module.exports = renderer
```

Then:

``` console
TypeError: Cannot read property 'indexOf' of undefined
    at AbstractHistory.parse (/Users/zhangshuyao/Sites/git/docs/node_modules/docsify-server-renderer/build.js:349:30)
    at Compiler.compile (/Users/zhangshuyao/Sites/git/docs/node_modules/docsify-server-renderer/build.js:553:37)
    at Renderer.<anonymous> (/Users/zhangshuyao/Sites/git/docs/node_modules/docsify-server-renderer/build.js:1126:28)
    at Generator.next (<anonymous>)
    at c (/Users/zhangshuyao/Sites/git/docs/node_modules/docsify-server-renderer/build.js:14:99)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
```

There is shotcut of `docsify-server-renderer/build.js`

``` js
// line 553
  var curFileName = this$1.router.parse().file;
// line 346-360
  AbstractHistory.prototype.parse = function parse (path$$1) {
    var query = '';

    var queryIndex = path$$1.indexOf('?');
    if (queryIndex >= 0) {
      query = path$$1.slice(queryIndex + 1);
      path$$1 = path$$1.slice(0, queryIndex);
    }

    return {
      path: path$$1,
      file: this.getFile(path$$1),
      query: parseQuery(query)
    }
  };
```

I think maybe there is something wrong with my code or `build.js` after rollup-build, pls help me to check it.

Best

**Comment by ccforeverd** [comment]
My work dir:
--src
  --docs
    --...
    --index.template.html
  --server
    --controller
      --docs-renderer.js
    --router
      --docs.js
      --index.js
    index.js
--package.json
--...

**Comment by ccforeverd** [comment]
``` js
// src/server/router/docs.js

require('colors')
const path = require('path')
const send = require('koa-send')
const renderer = require('../controller/docs-renderer')

const docsDir = path.resolve(__dirname, '../../docs')

const routerName = 'docs'
const routerPath = '/docs/(.*)?'
const routerHandler = async ctx => {
  const sendPath = ctx.path.replace(`/${routerName}`, '') || '/'
  const sendOptions = {
    root: docsDir,
    index: 'index.html'
  }

  try {
    await send(ctx, sendPath, sendOptions)
  } catch (e) {
    console.log(`[${'send'.magenta} ${'404'.red}] ${ctx.path}`)
  }
}

module.exports = {
  name: routerName,
  path: routerPath,
  handler: routerHandler
}

```

**Comment by ccforeverd** [comment]
When i visit http://localhost:3333/docs#/, it's all OK with router model hash. But if i try ssr, there is allways a error of parse.

Pls see before:

https://github.com/docsifyjs/docsify/blob/a257a4ab4eaaa5bf5e9345f0ffd6f5d9dd476c40/src/core/render/compiler.js#L121

https://github.com/docsifyjs/docsify/blob/a257a4ab4eaaa5bf5e9345f0ffd6f5d9dd476c40/src/core/router/history/abstract.js#L10

The method `parse` real need an argument of `path`

**Comment by yatagasaru** [comment]
I have the same problem

```
const Renderer = require('docsify-server-renderer')
const readFileSync = require('fs').readFileSync
const express = require ('express');

const app = express();

let renderer = new Renderer({
    template: readFileSync('./docs/index.template.html', 'utf-8'),
    config: {
        name: 'Test',
        basePath: '/docs',
        repo: 'te/st',
        loaddNavbar: true, 
        loadSidebar: true, 
        subMaxLevel: 3, 
        auto2top: true
    }
})
app.get('*', (req, res) =>{
    renderer.renderToString(req.url, (html, err) =>{
        if(err) throw err
        console.log(html)
    })
})
app.listen(3000, console.log("RUNING ON PORT 3000"))
```

```
TypeError: Cannot read property 'indexOf' of undefined
    at AbstractHistory.parse (/home/ga/tes/ns/doc/node_modules/docsify-server-renderer/build.js:349:30)
    at Compiler.compile (/home/ga/tes/ns/doc/node_modules/docsify-server-renderer/build.js:553:37)
    at Renderer.<anonymous> (/home/ga/tes/ns/doc/node_modules/docsify-server-renderer/build.js:1126:28)
    at Generator.next (<anonymous>)
    at c (/home/ga/tes/ns/doc/node_modules/docsify-server-renderer/build.js:14:99)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

**Comment by kaesar** [comment]
About `docsify-server-renderer/build.js`, I'd tested to change this ...
```js
// line 346-360
  AbstractHistory.prototype.parse = function parse (path$$1) {
    var query = '';

    var queryIndex = path$$1.indexOf('?');
    if (queryIndex >= 0) {
      query = path$$1.slice(queryIndex + 1);
      path$$1 = path$$1.slice(0, queryIndex);
    }

    return {
      path: path$$1,
      file: this.getFile(path$$1),
      query: parseQuery(query)
    }
  };
```
by ...
```js
// line 346-360
  AbstractHistory.prototype.parse = function parse (path$$1) {
    var query = '';
    var queryIndex = -1;                             // new
    if (path$$1) queryIndex = path$$1.indexOf('?');  // edited
    if (queryIndex >= 0) {
      query = path$$1.slice(queryIndex + 1);
      path$$1 = path$$1.slice(0, queryIndex);
    }

    return {
      path: path$$1,
      file: this.getFile(path$$1),
      query: parseQuery(query)
    }
  };
```
It works for me (around 349 line). Please, to check and release it if you consider it's ok.

**Comment by zmnv** [comment]
Same error! Just download https://github.com/docsifyjs/docsify-ssr-demo
```npm install```
```npm start```

```
[SSR] Serving . now.
Listening at http://localhost:4000

TypeError: Cannot read property 'indexOf' of undefined
```

**Comment by zmnv** [comment]
just download `master` branch. 

```
zmnv:docsify-master zmnv$ npm run serve:ssr

> docsify@4.8.6 serve:ssr /Users/user/docsify-master
> cross-env SSR=1 node server

Serving "/Users/user/docsify-master" at http://127.0.0.1:3000
Ready for changes
Ready for changes
(node:2594) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'indexOf' of undefined
```

**Comment by zmnv** [comment]
All works with old 4.1.7 version. Latest now: 4.3.0 – error.
```
"docsify-cli": "^4.1.7",
```

**Comment by zmnv** [comment]
No. Something wrong.. Can you update docsify-cli or ssr example repo, pls?

**Comment by llwor94** [comment]
i'm having the same issue... anyone have any luck?

**Comment by wll8** [comment]
It seems that the examples on `[docsify-ssr-demo](https://github.com/docsifyjs/docsify-ssr-demo)` are incomplete and incorrect.
I don't know why.

I don't know how [https://docsify.now.sh/ssr](https://docsify.now.sh/ssr) is implemented.

``` bash
git clone https://github.com/docsifyjs/docsify-ssr-demo
cd docsify-ssr-demo
npm i 
npm start
# open http://localhost:4000
# TypeError: Cannot read property 'indexOf' of undefined
``` 

``` bash
git clone https://github.com/docsifyjs/docsify
cd docsify
npm i
npm run dev:ssr
# open http://localhost:3000
# UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'indexOf' of undefined
```

**Comment by randyguogithub** [comment]
The same error found, even upgrade to the latest version of docsify

**Comment by jinguowu** [comment]
The same error found, even upgrade to the latest version of docsify  4.3

**Comment by loverajoel** [comment]
Same here, any update?

**Comment by naihe138** [comment]
The same error found, even upgrade to the latest version of docsify

**Comment by theBliz** [comment]
this is not solved yet. Doc not clear and the only example available breaks. Any updates?

**Comment by mattvb91** [comment]
Still having this issue. Did anyone manage to find a fix?

**Comment by boxsnake** [comment]
I looked around the code, and found the possible reason:
- It seems that the "main" render part resolve relative paths to absolute paths before rendering.
- And when `_renderFile` is called, for absolute paths, the function uses JS's `fetch` to get file.
- Since fetch is not available for local files without a `file://` scheme, the fetch won't work.
- As a result, the content is empty.

**Comment by equinusocio** [comment]
Same here
