### ISSUE TITLE
Docsify serve doesn't execute

### ISSUE THREAD

**Issue by marksq** [docsifyjs/docsify#764]
Hello!

I try to execute `docsify serve` on my PC and get the error:

```
docsify serve

Serving C:\Projects\docs now.
Listening at http://localhost:3000

C:\Users\user\AppData\Roaming\npm\node_modules\docsify-cli\node_modules\readable-stream\lib\_stream_readable.js:776
    processNextTick(resume_, stream, state);
    ^

TypeError: processNextTick is not a function
    at resume (C:\Users\user\AppData\Roaming\npm\node_modules\docsify-cli\node_modules\readable-stream\lib\_stream_readable.js:776:5)
    at ReaddirpReadable.Readable.resume (C:\Users\user\AppData\Roaming\npm\node_modules\docsify-cli\node_modules\readable-stream\lib\_stream_readable.js:768:5)
    at ReaddirpReadable.Readable.on (C:\Users\user\AppData\Roaming\npm\node_modules\docsify-cli\node_modules\readable-stream\lib\_stream_readable.js:738:53)
    at FSWatcher.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\docsify-cli\node_modules\chokidar\lib\nodefs-handler.js:362:8)
    at FSWatcher.NodeFsHandler._handleDir (C:\Users\user\AppData\Roaming\npm\node_modules\docsify-cli\node_modules\chokidar\lib\nodefs-handler.js:406:18)
    at FSWatcher.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\docsify-cli\node_modules\chokidar\lib\nodefs-handler.js:455:19)
    at FSWatcher.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\docsify-cli\node_modules\chokidar\lib\nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:155:5)
```

In the past, the command worked correctly and on my server the command works too. I think there is a problem with Node.js or with my environment but other Node.js apps work correctly.

I use Windows 8.1 and Node.js 10.15.1. What did I do wrong?

**Comment by timaschew** [comment]
This is the wrong repo, but it seems that you've removed a **dot**, which means you try to access a totally different function. For future you can look core function of Node.js on their docs: https://nodejs.org/api/process.html#process_process_nexttick_callback_args
