### ISSUE TITLE
Can't install on latest MacOS

### ISSUE THREAD

**Issue by dodalovic** [docsifyjs/docsify#798]
```
➜ npm i docsify-cli -g

/me/tools/graalvm-ee-1.0.0-rc13/Contents/Home/jre/languages/js/bin/docsify -> /me/tools/graalvm-ee-1.0.0-rc13/Contents/Home/jre/languages/js/lib/node_modules/docsify-cli/bin/docsify

> fsevents@1.2.7 install /me/tools/graalvm-ee-1.0.0-rc13/Contents/Home/jre/languages/js/lib/node_modules/docsify-cli/node_modules/fsevents
> node install

node-pre-gyp WARN Using needle for node-pre-gyp https download
[fsevents] Success: "/me/tools/graalvm-ee-1.0.0-rc13/Contents/Home/jre/languages/js/lib/node_modules/docsify-cli/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" is installed via remote

> docsify@4.9.1 postinstall /me/tools/graalvm-ee-1.0.0-rc13/Contents/Home/jre/languages/js/lib/node_modules/docsify-cli/node_modules/docsify
> opencollective postinstall

java.lang.UnsatisfiedLinkError: sun.misc.Unsafe.addressSize()I [symbol: Java_sun_misc_Unsafe_addressSize or Java_sun_misc_Unsafe_addressSize__]
	at com.oracle.svm.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:145)
	at com.oracle.svm.jni.JNIGeneratedMethodSupport.nativeCallAddress(JNIGeneratedMethodSupport.java:54)
	at sun.misc.Unsafe.addressSize(Unsafe.java)
	at java.nio.Bits.copySwapMemory(Bits.java:1013)
	at java.nio.Bits.copyToCharArray(Bits.java:867)
	at java.nio.DirectCharBufferS.get(DirectCharBufferS.java:275)
	at java.nio.CharBuffer.get(CharBuffer.java:715)
```

```
npm -v
6.9.0
```

```
MacOS Mojave: 10.14.4 (18E226)
```

**Comment by timaschew** [comment]
Seems to be related to graalvm.

**Comment by jhildenbiddle** [comment]
Looks like a java-related issue. macOS doesn't ship with Java pre-installed, so this may just be a matter of installing the Java SDK.

Try the following:

```bash
java --version
```

If you don't have java installed, macOS will display a prompt with a "More Info..." button that will take you to a Java SDK install page.
